services:
  broker:
    image: signet-broker:latest
    # ports:
      # - "8081:8081"
    networks:
      - backend

  nginx:
    build: ./server/nginx
    ports:
      - "20209:80"
      - "30209:443"
    networks:
      - frontend
      - backend
    depends_on:
      - broker

networks:
  frontend:
    driver: bridge
  backend:
